Media Files
zhoutwo/RHIT-Club-App pull request #2
Opened 2017-01-31 18:29 UTC by morschm

This should be how we can store and retrieve files. There might be too much here and less of writing/reading files is needed, or vice-versa.

2017-02-01 00:33 UTC, morschm commented
Just saw the router file was included. Not meant to be there. It will be deleted.

2017-02-01 22:30 UTC, zhoutwo requested changes

2017-02-01 22:30 UTC, zhoutwo commented on file/fileRouter.js
> +*/
You need a function to generate a file path

2017-02-01 22:30 UTC, zhoutwo commented on file/fileRouter.js
> +function postFile(file_id, file) {
Not file_id, but file path. Same for below.

2017-02-01 22:30 UTC, zhoutwo commented on file/fileRouter.js
> +function postFile(file_id, file) {
I assume that should be the request object, or at least some kind of streamable object?

2017-02-15 06:46 UTC, zhoutwo approved these changes

2017-02-15 06:49 UTC, merged